version: '3.8'

services:
  hellojohn-db:
    image: postgres:15-alpine
    container_name: hellojohn-db
    environment:
      POSTGRES_USER: hellojohn
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: hellojohn_db
    ports:
      - "5433:5432"
    volumes:
      - hellojohn_db_data:/var/lib/postgresql/data
    networks:
      - hellojohn-net

  hellojohn-redis:
    image: redis:7-alpine
    container_name: hellojohn-redis
    ports:
      - "6380:6379"
    volumes:
      - hellojohn_redis_data:/data
    networks:
      - hellojohn-net

networks:
  hellojohn-net:
    driver: bridge

volumes:
  hellojohn_db_data:
  hellojohn_redis_data:
